name = "lace-shop"
compatibility_date = "2024-01-01"
main = ".next/server/pages/api/_worker.js"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"
cwd = "."
watch_dir = "."

[build.upload]
format = "service-worker"

[site]
bucket = ".next"

[env.production]
name = "lace-shop"

[[kv_namespaces]]
binding = "PRODUCTS"
id = "your_products_namespace_id"

[functions]
directory = "functions"
