name = "lace-shop"
main = ".next/server/pages/api/_worker.js"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[build]
command = "NODE_ENV=production npm run pages:build"

[site]
bucket = ".next"

[functions]
directory = "functions"

[[kv_namespaces]]
binding = "PRODUCTS"
id = "PRODUCTS"
