name = "lace-shop"
compatibility_date = "2024-01-01"
main = "workers-site/index.js"

[[kv_namespaces]]
binding = "PRODUCTS"
preview_id = "preview_products"
id = "your_products_namespace_id"

[[r2_buckets]]
binding = "VIDEOS"
bucket_name = "lace-shop-videos"

[vars]
ENVIRONMENT = "production"

[site]
bucket = "./out"
